<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>tiangong_nav_bringup</name>
  <version>1.2.0</version>
  <description>Robot-specific RTAB-Map and Nav2 bringup configuration.</description>
  <maintainer email="tianhong.huang@ubtrobot.com">Tianhong Huang</maintainer>
  <license file="LICENSE-Apache-2.0">Apache-2.0</license>
  <license file="LICENSE-BSD-3-Clause">BSD-3-Clause</license>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>nav2_bringup</exec_depend>
  <exec_depend>rtabmap_slam</exec_depend>
  <exec_depend>rtabmap_util</exec_depend>
  <exec_depend>tf2_ros</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
